name: pedidos_gastronomicos
description: Sistema de pedidos para emprendimientos gastronómicos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Backend & Database
  supabase_flutter: ^2.3.4

  # Image Handling
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  # UI Components
  flutter_svg: ^2.0.10

  # Utilities
  intl: ^0.20.2  # Para formatear fechas y monedas
  uuid: ^4.3.3   # Para generar IDs únicos si es necesario

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Aquí agregarás tus assets más adelante
  # assets:
  #   - assets/images/
  #   - assets/icons/